/**
 * Multi-Page Document Example
 * Demonstrates page break handling for documents with multiple pages
 */

import React from 'react';
import { Document, Page, Text, pdf } from '@react-pdf/renderer';
import { commonStyles } from '../styles/common.styles';
import { Header, Section, Field, Footer } from '../components/common';
import { PDFTemplate, PDFGenerationOptions } from '../types';
import {
  KeepTogether,
  NoBreak,
  BreakableSection,
  FixedSection,
  ContentBlock,
  OrphanControl
} from '../utils/page-breaks';

interface ReportData {
  title: string;
  summary: string;
  sections: Array<{
    title: string;
    items: Array<{
      label: string;
      value: string;
    }>;
  }>;
  notes: string[];
}

interface MultiPageReportProps {
  data: ReportData;
  options?: PDFGenerationOptions;
}

const MultiPageReport: React.FC<MultiPageReportProps> = ({ data, options }) => {
  return (
    <Document
      author={options?.author || 'Team Ops Dashboard'}
      title={options?.title || data.title}
      subject={options?.subject || 'Multi-Page Report'}
    >
      <Page size="A4" style={commonStyles.page}>
        {/* Page 1: Header and Summary */}
        <NoBreak>
          <Header
            title={data.title}
            subtitle="Multi-Page Document Example"
          />
        </NoBreak>

        <FixedSection>
          <Section title="Executive Summary">
            <Text style={commonStyles.fieldValue}>{data.summary}</Text>
          </Section>
        </FixedSection>

        {/* Sections that can break naturally */}
        {data.sections.slice(0, 2).map((section, index) => (
          <BreakableSection key={index} title={section.title}>
            {section.items.map((item, itemIndex) => (
              <OrphanControl key={itemIndex}>
                <Field label={item.label} value={item.value} />
              </OrphanControl>
            ))}
          </BreakableSection>
        ))}

        {/* Footer on first page */}
        <Footer
          leftText="Generated by Team Ops Dashboard"
          rightText="Page 1 of 2"
        />
      </Page>

      {/* Force new page */}
      <Page size="A4" style={commonStyles.page}>
        {/* Page 2: Additional sections */}
        <NoBreak>
          <Header
            title={data.title}
            subtitle="Continued"
          />
        </NoBreak>

        {/* Remaining sections */}
        {data.sections.slice(2).map((section, index) => (
          <KeepTogether key={index}>
            <Section title={section.title} wrap={false}>
              {section.items.map((item, itemIndex) => (
                <Field key={itemIndex} label={item.label} value={item.value} />
              ))}
            </Section>
          </KeepTogether>
        ))}

        {/* Notes section with natural breaking */}
        {data.notes.length > 0 && (
          <BreakableSection title="Notes">
            {data.notes.map((note, index) => (
              <ContentBlock key={index} wrap={true} minPresenceAhead={30}>
                <Text style={[commonStyles.fieldValue, commonStyles.mb10]}>
                  {index + 1}. {note}
                </Text>
              </ContentBlock>
            ))}
          </BreakableSection>
        )}

        {/* Footer on second page */}
        <Footer
          leftText="Generated by Team Ops Dashboard"
          rightText="Page 2 of 2"
        />
      </Page>
    </Document>
  );
};

/**
 * Generate Multi-Page Report PDF
 */
const generateMultiPageReport = async (
  data: ReportData,
  options?: PDFGenerationOptions
): Promise<Buffer> => {
  const document = <MultiPageReport data={data} options={options} />;
  const asPdf = pdf(document);
  const blob = await asPdf.toBlob();
  const arrayBuffer = await blob.arrayBuffer();
  return Buffer.from(arrayBuffer);
};

/**
 * Multi-Page Report PDF Template Export
 */
export const multiPageReportTemplate: PDFTemplate<ReportData> = {
  name: 'multi-page-report',
  generate: generateMultiPageReport,
};
