/**
 * Table with Page Breaks Example
 * Demonstrates proper table pagination
 */

import React from 'react';
import { Document, Page, Text, View, pdf } from '@react-pdf/renderer';
import { commonStyles } from '../styles/common.styles';
import { Header, Footer } from '../components/common';
import { PDFTemplate, PDFGenerationOptions } from '../types';
import { NoBreak, TableRow } from '../utils/page-breaks';

interface TableItem {
  id: string;
  name: string;
  status: string;
  date: string;
  assignee: string;
}

interface TableData {
  title: string;
  columns: string[];
  rows: TableItem[];
}

interface TableReportProps {
  data: TableData;
  options?: PDFGenerationOptions;
}

const TableReport: React.FC<TableReportProps> = ({ data, options }) => {
  return (
    <Document
      author={options?.author || 'Team Ops Dashboard'}
      title={options?.title || data.title}
      subject={options?.subject || 'Table Report'}
    >
      <Page size="A4" style={commonStyles.page}>
        {/* Header */}
        <NoBreak>
          <Header
            title={data.title}
            subtitle="Table Report with Pagination"
          />
        </NoBreak>

        {/* Table */}
        <View style={commonStyles.table}>
          {/* Table Header - Keep together and repeat on each page */}
          <NoBreak>
            <View style={commonStyles.tableHeader} fixed>
              {data.columns.map((column, index) => (
                <Text key={index} style={commonStyles.tableCell}>
                  {column}
                </Text>
              ))}
            </View>
          </NoBreak>

          {/* Table Rows - Each row stays together but table can break between rows */}
          {data.rows.map((row) => (
            <TableRow key={row.id}>
              <Text style={commonStyles.tableCell}>{row.id}</Text>
              <Text style={commonStyles.tableCell}>{row.name}</Text>
              <Text style={commonStyles.tableCell}>{row.status}</Text>
              <Text style={commonStyles.tableCell}>{row.date}</Text>
              <Text style={commonStyles.tableCell}>{row.assignee}</Text>
            </TableRow>
          ))}
        </View>

        {/* Footer */}
        <Footer
          leftText="Generated by Team Ops Dashboard"
          rightText="Page"
        />
      </Page>
    </Document>
  );
};

/**
 * Generate Table Report PDF
 */
const generateTableReport = async (
  data: TableData,
  options?: PDFGenerationOptions
): Promise<Buffer> => {
  const document = <TableReport data={data} options={options} />;
  const asPdf = pdf(document);
  const blob = await asPdf.toBlob();
  const arrayBuffer = await blob.arrayBuffer();
  return Buffer.from(arrayBuffer);
};

/**
 * Table Report PDF Template Export
 */
export const tableReportTemplate: PDFTemplate<TableData> = {
  name: 'table-report',
  generate: generateTableReport,
};
