/**
 * Enhanced Task Details PDF Template
 * Demonstrates comprehensive page break handling
 */

import React from 'react';
import { Document, Page, Text, View, pdf } from '@react-pdf/renderer';
import { Task } from '@/shared/types/task';
import { commonStyles } from '../styles/common.styles';
import { Header, Section, Field, Badge, Footer } from '../components/common';
import { formatDate, formatStatus, formatPriority } from '../utils/formatters';
import { PDFTemplate, PDFGenerationOptions } from '../types';
import {
  KeepTogether,
  NoBreak,
  BreakableSection,
  FixedSection,
  ContentBlock
} from '../utils/page-breaks';

interface TaskDetailsPDFProps {
  task: Task;
  options?: PDFGenerationOptions;
}

const TaskDetailsPDF: React.FC<TaskDetailsPDFProps> = ({ task, options }) => {
  const getStatusBadgeVariant = (status: string) => {
    switch (status) {
      case 'COMPLETED':
        return 'success';
      case 'IN_PROGRESS':
        return 'primary';
      case 'CANCELLED':
        return 'danger';
      default:
        return 'secondary';
    }
  };

  const getPriorityBadgeVariant = (priority: string) => {
    switch (priority) {
      case 'URGENT':
        return 'danger';
      case 'HIGH':
        return 'warning';
      case 'MEDIUM':
        return 'primary';
      default:
        return 'secondary';
    }
  };

  return (
    <Document
      author={options?.author || 'Team Ops Dashboard'}
      title={options?.title || `Task: ${task.name}`}
      subject={options?.subject || 'Task Details'}
    >
      <Page size="A4" style={commonStyles.page}>
        {/* Header - Never breaks across pages */}
        <NoBreak>
          <Header
            title="Task Details"
            subtitle={`Generated on ${formatDate(new Date().toISOString())}`}
          />
        </NoBreak>

        {/* Task Information - Stays together on one page */}
        <FixedSection minPresenceAhead={80}>
          <Section title="Task Information" wrap={false}>
            <Field label="Task ID" value={task.id} />
            <Field label="Task Name" value={task.name} />

            <View style={commonStyles.field}>
              <Text style={commonStyles.fieldLabel}>Status</Text>
              <Badge
                text={formatStatus(task.status)}
                variant={getStatusBadgeVariant(task.status)}
              />
            </View>

            <View style={commonStyles.field}>
              <Text style={commonStyles.fieldLabel}>Priority</Text>
              <Badge
                text={formatPriority(task.priority)}
                variant={getPriorityBadgeVariant(task.priority)}
              />
            </View>

            <Field label="Due Date" value={formatDate(task.dueDate)} />
          </Section>
        </FixedSection>

        {/* Description - Can break naturally for long text */}
        {task.description && (
          <BreakableSection title="Description">
            <ContentBlock wrap={true} minPresenceAhead={50}>
              <Text style={commonStyles.fieldValue}>{task.description}</Text>
            </ContentBlock>
          </BreakableSection>
        )}

        {/* Assignment Details - Keep related fields together */}
        <KeepTogether>
          <Section title="Assignment Details" wrap={false}>
            <Field
              label="Assigned To"
              value={task.assignedTo?.name || task.assignedToId}
            />
            {task.assignedTo?.email && (
              <Field label="Assignee Email" value={task.assignedTo.email} />
            )}
            {task.team?.name && <Field label="Team" value={task.team.name} />}
          </Section>
        </KeepTogether>

        {/* Creation Details - Keep together */}
        <KeepTogether>
          <Section title="Creation Details" wrap={false}>
            <Field
              label="Created By"
              value={task.createdBy?.name || task.createdById}
            />
            <Field label="Created At" value={formatDate(task.createdAt)} />
            <Field label="Last Updated" value={formatDate(task.updatedAt)} />
          </Section>
        </KeepTogether>

        {/* Footer - Fixed at bottom of page */}
        <Footer
          leftText="Generated by Team Ops Dashboard"
          rightText="Page 1 of 1"
        />
      </Page>
    </Document>
  );
};

/**
 * Generate Task Details PDF
 */
const generateTaskDetailsPDF = async (
  data: Task,
  options?: PDFGenerationOptions
): Promise<Buffer> => {
  const document = <TaskDetailsPDF task={data} options={options} />;
  const asPdf = pdf(document);
  const blob = await asPdf.toBlob();
  const arrayBuffer = await blob.arrayBuffer();
  return Buffer.from(arrayBuffer);
};

/**
 * Enhanced Task Details PDF Template Export
 */
export const taskDetailsPDFTemplateEnhanced: PDFTemplate<Task> = {
  name: 'task-details-enhanced',
  generate: generateTaskDetailsPDF,
};
